export const ARTICLES = [
  {
    folder: '06-types-of-4d-bets',
    slug: 'types-of-4d-bets',
    images: [
      {
        file: 'types-of-4d-bets-hero',
        type: 'hero',
        alt: 'Types of 4D bets explained including fixed, permutation and iBet entries',
        caption: 'Every bet type on the slip, decoded.',
        data: {
          kicker: 'BET TYPES',
          title: 'Types of 4D Bets Explained',
          subtitle: 'Fixed, Permutation, iBet and system entries: costs, coverage and payouts.',
          digits: [1, 2, 3, 4],
        },
      },
      {
        file: 'types-of-4d-bets-comparison',
        type: 'table',
        alt: 'Comparison table of 4D bet types showing combinations, cost and best use',
        caption: 'What each bet type costs and covers.',
        data: {
          kicker: 'COMPARE',
          title: 'Bet Types at a Glance',
          columns: [
            { label: 'Bet type', w: 2.4 },
            { label: 'Combinations', w: 2 },
            { label: 'Cost per RM1 base', w: 2.4 },
            { label: 'Best for', w: 3.4 },
          ],
          rows: [
            ['Single / Fixed', '1 exact order', 'RM1', 'Confident on one number'],
            ['Permutation 24', '24 orders', 'RM24', 'Any order, 4 distinct digits'],
            ['Permutation 12', '12 orders', 'RM12', 'Three same digits, e.g. 1123'],
            ['Permutation 6', '6 orders', 'RM6', 'Two pairs, e.g. 1122'],
            ['Permutation 4', '4 orders', 'RM4', 'Three same digits, e.g. 1112'],
            ['iBet', '12 or 24 orders', 'RM1', 'Budget any-order play, lower payout'],
          ],
          note: 'Permutation and iBet payouts are reduced per combination. Costs shown per RM1 base stake.',
        },
      },
      {
        file: 'types-of-4d-bets-permutation-payouts',
        type: 'table',
        alt: 'Permutation 4D payout table showing Big and Small prizes for 24, 12, 6 and 4 combination bets',
        caption: 'Official permutation payout grid.',
        data: {
          kicker: 'PAYOUT GRID',
          title: 'Permutation Payouts per RM1',
          columns: [
            { label: 'Prize tier', w: 2.4 },
            { label: 'Perm 24', w: 1.8 },
            { label: 'Perm 12', w: 1.8 },
            { label: 'Perm 6', w: 1.8 },
            { label: 'Perm 4', w: 1.8 },
          ],
          rows: [
            ['Big 1st', 'RM105', 'RM209', 'RM417', 'RM625'],
            ['Big 2nd', 'RM42', 'RM84', 'RM167', 'RM250'],
            ['Big 3rd', 'RM21', 'RM42', 'RM84', 'RM125'],
            ['Small 1st', 'RM146', 'RM292', 'RM584', 'RM875'],
            ['Special', 'RM8', 'RM15', 'RM30', 'RM45'],
            ['Consolation', 'RM3', 'RM5', 'RM10', 'RM15'],
          ],
          note: 'Sports Toto published table, per RM1. Similar structures apply across pools. Verify before claiming.',
        },
      },
      {
        file: 'types-of-4d-bets-permutation-example',
        type: 'steps',
        alt: 'Example showing how a 4D permutation bet covers every order of a number',
        caption: 'How a permutation bet works, step by step.',
        data: {
          kicker: 'EXAMPLE',
          title: 'Permutation Bet on 1234',
          items: [
            { h: 'You pick 1234 as Perm 24', p: 'The slip records a permutation of 24 with a RM1 base, so the total cost is RM24.' },
            { h: 'All 24 digit orders are covered', p: '1234, 1243, 1324, 3214, 4321 and every other arrangement count as yours.' },
            { h: 'Any matching order wins', p: 'If the draw shows 4321, a straight bet would miss. A permutation pays out.' },
            { h: 'Payout per combination is lower', p: 'The stake is spread across 24 combinations, so each pays a fraction of the fixed-bet prize.' },
          ],
          note: 'Fewer unique digits means fewer permutations: 1123 gives 12, 1122 gives 6, 1112 gives 4.',
        },
      },
      {
        file: 'types-of-4d-bets-which-to-pick',
        type: 'card',
        alt: 'Guide to choosing the right 4D bet type for budget and play style',
        caption: 'Match the bet to your budget.',
        data: {
          kicker: 'DECIDE',
          title: 'Which Bet Type Should You Pick?',
          heading: 'Choose by budget first, payout second',
          bullets: [
            'Fixed bet: highest payout, but the digits must land in exact order.',
            'Permutation: pays for coverage, good if you never trust the order.',
            'iBet: cheapest way to cover any order, with the smallest payouts.',
            'Big vs Small changes tier coverage more than most players realise.',
            'Write down your total stake before confirming. Permutations multiply cost fast.',
            'Set a hard budget per draw. Bet type does not change the odds of the number hitting.',
          ],
          warn: 'Gambling involves risk. Only stake what you can afford to lose. 21 and above.',
        },
      },
    ],
  },
  {
    folder: '07-4d-winnings-tax-malaysia',
    slug: '4d-winnings-tax-malaysia',
    images: [
      {
        file: '4d-winnings-tax-malaysia-hero',
        type: 'hero',
        alt: 'Whether 4D lottery winnings in Malaysia are subject to income tax',
        caption: 'The tax question every winner asks.',
        data: {
          kicker: 'TAX',
          title: 'Are 4D Winnings Taxable in Malaysia?',
          subtitle: 'What applies to casual wins, big wins, and betting treated as a trade.',
          digits: [6, 0, 0, 9],
        },
      },
      {
        file: '4d-winnings-tax-malaysia-how-looks',
        type: 'steps',
        alt: 'Steps explaining how LHDN treats 4D lottery winnings and when tax may apply',
        caption: 'How winnings are generally treated.',
        data: {
          kicker: 'POSITION',
          title: 'How Gambling Winnings Are Treated',
          items: [
            { h: 'Casual win is not employment income', p: 'A one-off lottery prize is a windfall. It is not salary, so it is not taxed as such for most players.' },
            { h: 'Frequency changes the picture', p: 'If betting becomes systematic, regular and profit-driven, LHDN may view it as a trade or business.' },
            { h: 'Records decide disputes', p: 'Tickets, dates, stakes and claim receipts are what you show if your pattern of play is ever questioned.' },
            { h: 'Business income must be declared', p: 'If your activity is treated as a trade, the profit is taxable and losses may not be claimable against other income.' },
          ],
          note: 'General information only, not tax advice. Confirm your position with LHDN or a licensed tax agent.',
        },
      },
      {
        file: '4d-winnings-tax-malaysia-scenarios',
        type: 'table',
        alt: 'Table of 4D winnings tax scenarios in Malaysia with treatment and recommended actions',
        caption: 'Scenario-by-scenario treatment.',
        data: {
          kicker: 'SCENARIOS',
          title: 'Tax Treatment by Situation',
          columns: [
            { label: 'Situation', w: 3 },
            { label: 'General treatment', w: 3.4 },
            { label: 'What you should do', w: 3.6 },
          ],
          rows: [
            ['Occasional win on a RM10 bet', 'Windfall. Not taxed as income for most players', 'Keep the ticket photo and claim record'],
            ['Large one-off win', 'Generally not taxed, but document everything', 'Keep IC copy, ticket and HQ claim receipt'],
            ['Betting every draw as a habit', 'May be seen as a trade if systematic and profit-led', 'Ask a tax agent before it becomes an issue'],
            ['Running bets for others', 'Trading income, plus legal risk if unlicensed', 'Stop. Unlicensed bookmaking is illegal'],
          ],
          note: 'Rules and interpretations can change. Get professional advice for your own circumstances.',
        },
      },
      {
        file: '4d-winnings-tax-malaysia-records',
        type: 'card',
        alt: 'Record keeping checklist for 4D winnings claims and tax documentation in Malaysia',
        caption: 'Paper trail: keep it, always.',
        data: {
          kicker: 'RECORDS',
          title: 'Record-Keeping Checklist',
          heading: 'What to keep after every win',
          bullets: [
            'A photo of the winning ticket before you claim, front and back.',
            'The draw date, operator and prize tier that matched.',
            'Your stake amount and bet type: Big, Small or permutation.',
            'The claim receipt and where you claimed: outlet, HQ or agent.',
            'IC details used for the claim, plus the date of claim.',
            'A simple yearly log if you play often: total staked vs total won.',
          ],
          warn: 'This site provides general information, not tax or legal advice.',
        },
      },
      {
        file: '4d-winnings-tax-malaysia-claim-essentials',
        type: 'table',
        alt: 'Table showing what to bring when claiming a 4D prize in Malaysia',
        caption: 'What you need at claim time.',
        data: {
          kicker: 'CLAIMING',
          title: 'Prize Claim Essentials',
          columns: [
            { label: 'Item', w: 3 },
            { label: 'Why it matters', w: 5.4 },
          ],
          rows: [
            ['Original winning ticket', 'It is a bearer document. Anyone holding it can claim, so sign the back.'],
            ['MyKad (IC)', 'Identity must match the claimant. Prizes are paid to the presenter of a valid ticket.'],
            ['Draw date and result check', 'Confirms the ticket is for the right draw before you travel.'],
            ['Outlets have cash limits', 'Small prizes are paid over the counter. Big wins go to operator headquarters.'],
            ['Keep the receipt', 'Your proof of claim and your record if tax treatment is ever queried.'],
          ],
          note: 'Claim windows and thresholds differ by operator. Check the operator prize claim rules first.',
        },
      },
    ],
  },
  {
    folder: '08-4d-odds-probability',
    slug: '4d-odds-probability',
    images: [
      {
        file: '4d-odds-probability-hero',
        type: 'hero',
        alt: '4D odds and probability of winning the lottery explained with maths',
        caption: 'The maths behind the four digits.',
        data: {
          kicker: 'PROBABILITY',
          title: '4D Odds: The Real Chance of Winning',
          subtitle: '10,000 combinations, 23 winners, and exactly what your RM1 returns.',
          digits: [1, 0, 0, 0],
        },
      },
      {
        file: '4d-odds-probability-tier-chart',
        type: 'chart',
        alt: 'Chart showing 4D winning odds by prize tier from 1st prize to any prize',
        caption: 'Odds at each tier, drawn to scale.',
        data: {
          kicker: 'ODDS LADDER',
          title: 'Chance of Winning by Tier (1 in X)',
          unitLabel: 'Winning numbers per 10,000 combinations. Longer bar = better odds',
          bars: [
            { label: 'Any prize on a Big bet', value: 23, display: '1 in 435' },
            { label: 'Special prize only', value: 10, display: '1 in 1,000' },
            { label: 'Top 3 prize', value: 3, display: '1 in 3,333' },
            { label: '1st prize', value: 1, display: '1 in 10,000', sqrtScale: true },
          ],
          note: 'Based on 10,000 combinations (0000 to 9999) and 23 published winning numbers per draw.',
        },
      },
      {
        file: '4d-odds-probability-expected-return',
        type: 'table',
        alt: 'Expected return table showing what a RM1 4D bet returns in the long run',
        caption: 'What RM1 is worth, mathematically.',
        data: {
          kicker: 'EXPECTED VALUE',
          title: 'Expected Return per RM1 Bet',
          columns: [
            { label: 'Tier', w: 3 },
            { label: 'Big returns', w: 2.4 },
            { label: 'Small returns', w: 2.4 },
          ],
          rows: [
            ['1st prize (1 in 10,000)', 'RM0.25', 'RM0.35'],
            ['2nd prize (1 in 10,000)', 'RM0.10', 'RM0.20'],
            ['3rd prize (1 in 10,000)', 'RM0.05', 'RM0.10'],
            ['Special (10 in 10,000)', 'RM0.18', 'RM0.00'],
            ['Consolation (10 in 10,000)', 'RM0.06', 'RM0.00'],
            ['Total expected return', 'RM0.64', 'RM0.65'],
          ],
          note: 'Roughly 64 to 65 sen comes back per RM1 over the long run, a house edge near 35 percent.',
        },
      },
      {
        file: '4d-odds-probability-fixed-rules',
        type: 'steps',
        alt: 'Key probability rules that make 4D odds fixed on every draw',
        caption: 'Why no system can beat the draw.',
        data: {
          kicker: 'THE RULES',
          title: 'Four Rules That Never Change',
          items: [
            { h: 'There are exactly 10,000 combinations', p: 'From 0000 to 9999. Your number occupies one slot out of ten thousand, every single draw.' },
            { h: 'Each draw is independent', p: 'The machine has no memory. Last week result has zero influence on this week draw.' },
            { h: 'The odds do not drift', p: 'A number drawn ten times this month still has the same 1-in-10,000 chance next draw.' },
            { h: 'The payout sets the edge', p: 'Operators price the prize table so they keep about 35 to 36 percent of all stakes, statistically.' },
          ],
          note: 'Systems, apps and prediction formulas change nothing about these four rules.',
        },
      },
      {
        file: '4d-odds-probability-reality-check',
        type: 'card',
        alt: 'Reality check card summarising 4D odds and responsible gambling facts',
        caption: 'Read this before chasing a system.',
        data: {
          kicker: 'REALITY CHECK',
          title: 'The Honest Summary',
          heading: 'What the numbers actually say',
          bullets: [
            'RM1 staked returns about 64 to 65 sen on average. Entertainment, not investment.',
            'A Big bet wins something roughly 1 time in 435 draws on that number.',
            'Hitting 1st prize is 1 in 10,000 per number, per draw.',
            'No wheeling system, app or hot-number list shifts those odds.',
            'Fixed budget, fixed stakes, no chasing losses.',
          ],
          warn: 'Gambling is entertainment with a cost. 21 and above. Play responsibly.',
        },
      },
    ],
  },
  {
    folder: '09-most-frequent-4d-numbers',
    slug: 'most-frequent-4d-numbers',
    images: [
      {
        file: 'most-frequent-4d-numbers-hero',
        type: 'hero',
        alt: 'Most frequent 4D winning numbers and frequency statistics from past draws',
        caption: 'Frequency data, and what it really proves.',
        data: {
          kicker: 'STATISTICS',
          title: 'Most Frequent 4D Numbers: The Data',
          subtitle: 'What years of published results show, and why it still predicts nothing.',
          digits: [7, 7, 8, 8],
        },
      },
      {
        file: 'most-frequent-4d-numbers-distribution',
        type: 'chart',
        alt: 'Chart showing how many times each 4D number wins 1st prize over 1,000 draws',
        caption: 'Most numbers never win at all.',
        data: {
          kicker: 'DISTRIBUTION',
          title: '1st-Prize Hits Per Number, Over 1,000 Draws',
          unitLabel: 'How many of the 10,000 numbers land 1st prize this many times',
          bars: [
            { label: 'Never wins (0 times)', value: 9048, display: '9,048 numbers' },
            { label: 'Wins once (1 time)', value: 904, display: '904 numbers' },
            { label: 'Wins twice (2 times)', value: 45, display: '45 numbers' },
            { label: 'Wins three times', value: 1, display: '1 number' },
          ],
          note: 'Theoretical distribution using a 1-in-10,000 chance per draw. Real archives behave the same way.',
        },
      },
      {
        file: 'most-frequent-4d-numbers-claims-table',
        type: 'table',
        alt: 'Table comparing popular 4D number myths against the statistical reality',
        caption: 'Common claims, checked against the maths.',
        data: {
          kicker: 'MYTH VS FACT',
          title: 'What Frequency Data Really Says',
          columns: [
            { label: 'Common claim', w: 4 },
            { label: 'The reality', w: 5 },
          ],
          rows: [
            ['7788 is overdue, it must hit soon', 'Every draw is independent. The number has the same odds as always.'],
            ['Hot numbers are luckier', 'Short-run frequency evens out. Long-run results match the theoretical average.'],
            ['Avoid cold numbers', 'Cold numbers carry exactly the same 1-in-10,000 chance.'],
            ['Patterns reveal future draws', 'Draws are random mechanical events. No pattern carries forward.'],
            ['A tracking app improves your odds', 'It cannot. The odds are fixed by the total combination count.'],
          ],
          note: 'Statistics describe the past. They do not move the probability of the next draw.',
        },
      },
      {
        file: 'most-frequent-4d-numbers-how-to-build',
        type: 'steps',
        alt: 'Steps to build your own 4D number frequency analysis from official results',
        caption: 'Build a frequency list the honest way.',
        data: {
          kicker: 'METHOD',
          title: 'Build Your Own Frequency List',
          items: [
            { h: 'Collect official results', p: 'Pull the full board from each operator for the period you want to analyse. Never mix operators.' },
            { h: 'Count each number', p: 'Tally how often every 4-digit number appears, split by prize tier rather than lumped together.' },
            { h: 'Compare with the expected average', p: 'Over 1,000 draws each number should win 1st prize about 0.1 times. Deviation is normal.' },
            { h: 'Report it honestly', p: 'Label the sample size and date range. A short window produces dramatic but meaningless swings.' },
          ],
          note: 'This is a fun data exercise. It is not a prediction tool and should never drive your stakes.',
        },
      },
      {
        file: 'most-frequent-4d-numbers-disclaimer',
        type: 'card',
        alt: 'Disclaimer card explaining limits of 4D number statistics and responsible play',
        caption: 'The fine print, in plain English.',
        data: {
          kicker: 'DISCLAIMER',
          title: 'If You Play, Read This',
          heading: 'Statistics are descriptive, not predictive',
          bullets: [
            'No number is due. No number is hot. The draw does not remember.',
            'Frequency analysis can describe history and nothing more.',
            'Never increase your stake because a list looks promising.',
            'Fix a budget per draw and treat any loss as the cost of entertainment.',
            'Lottery play is for adults aged 21 and above only.',
          ],
          warn: 'Gambling can be addictive. If betting is affecting your life, stop and seek help.',
        },
      },
    ],
  },
  {
    folder: '10-is-4d-legal-malaysia',
    slug: 'is-4d-legal-malaysia',
    images: [
      {
        file: 'is-4d-legal-malaysia-hero',
        type: 'hero',
        alt: 'Whether 4D lottery betting is legal in Malaysia including licences and online play',
        caption: 'Legal, illegal, and the grey in between.',
        data: {
          kicker: 'LEGAL',
          title: 'Is 4D Legal in Malaysia?',
          subtitle: 'Licensed operators, online play, and where the law draws the line.',
          digits: [2, 1, 0, 5],
        },
      },
      {
        file: 'is-4d-legal-malaysia-legal-vs-illegal',
        type: 'vs',
        alt: 'Comparison of legal licensed 4D play and illegal unlicensed betting in Malaysia',
        caption: 'Licensed play on the left, illegal activity on the right.',
        data: {
          kicker: 'THE LINE',
          title: 'Licensed vs Unlicensed 4D Activity',
          left: {
            head: 'Legal and licensed',
            rows: [
              'Buying tickets from Magnum, Sports Toto or Da Ma Cai outlets',
              'Official websites, apps and authorised agents',
              'Checking results on any site, free of charge',
              'Claiming prizes with an original ticket and IC',
            ],
          },
          right: {
            head: 'Illegal and high risk',
            dash: true,
            rows: [
              'Side bets with unlicensed bookies or runners',
              'Deposits into unlicensed betting apps or sites',
              'Running a betting operation without a licence',
              'Sharing IC or bank details to unlock fake results',
            ],
          },
          note: 'This site publishes results and guides only. It does not take or place bets.',
        },
      },
      {
        file: 'is-4d-legal-malaysia-how-licensed-works',
        type: 'flow',
        alt: 'Flow showing how licensed 4D operators are regulated and publish results in Malaysia',
        caption: 'From licence to published result.',
        data: {
          kicker: 'HOW IT WORKS',
          title: 'The Licensed 4D Chain',
          steps: [
            { h: 'Licence issued', p: 'Operators run draws under licences granted under Malaysian gaming law.' },
            { h: 'Regulated draw', p: 'Draws are conducted on approved days and formats under licence conditions.' },
            { h: 'Results published', p: 'The full 23-number board is released to the public the same evening.' },
            { h: 'Prizes paid', p: 'Winners claim at outlets or headquarters with the original ticket and IC.' },
          ],
          note: 'Gaming law includes the Common Gaming Houses Act 1953 and related legislation. Verify current rules yourself.',
        },
      },
      {
        file: 'is-4d-legal-malaysia-activities-table',
        type: 'table',
        alt: 'Table showing the legal status of different 4D related activities in Malaysia',
        caption: 'What is allowed and what is not.',
        data: {
          kicker: 'STATUS',
          title: 'Activity Legal Status',
          columns: [
            { label: 'Activity', w: 4 },
            { label: 'Status', w: 2.4 },
            { label: 'Notes', w: 3.6 },
          ],
          rows: [
            ['Buying tickets from licensed outlets', 'Legal', 'The standard, licensed channel'],
            ['Playing via official operator online channels', 'Legal', 'Use only the official domain'],
            ['Reading 4D results on info sites', 'Legal', 'Viewing public results is free'],
            ['Bets with unlicensed bookies or agents', 'Illegal', 'No consumer protection, fraud risk'],
            ['Deposits into unlicensed betting apps', 'Illegal', 'Money may be seized or lost'],
            ['Operating a betting shop without a licence', 'Illegal', 'Criminal offence under gaming law'],
          ],
          note: 'Age rules apply: gambling is restricted to adults. Check the current requirement before you play.',
        },
      },
      {
        file: 'is-4d-legal-malaysia-safety-checklist',
        type: 'card',
        alt: 'Safety checklist for staying legal when checking and playing 4D in Malaysia',
        caption: 'Stay on the right side of the line.',
        data: {
          kicker: 'STAY SAFE',
          title: 'Legal and Safe: Checklist',
          heading: 'Six rules that keep you protected',
          bullets: [
            'Play only through licensed operators and their official channels.',
            'Never place bets with bookies, runners or unlicensed apps.',
            'Checking results is free. Never pay for a result or a tip.',
            'Never hand over IC, bank or OTP details to a results site.',
            'Gambling is for those aged 21 and above.',
            'Report suspected illegal operations to the police instead of participating.',
          ],
          warn: 'Laws change. Confirm current rules with official sources before acting.',
        },
      },
    ],
  },
];
