export const ARTICLES = [
  {
    folder: '01-4d-result-today',
    slug: '4d-result-today',
    images: [
      {
        file: '4d-result-today-hero',
        type: 'hero',
        alt: '4D result today board for Magnum, Sports Toto and Da Ma Cai on 4DMalaya',
        caption: 'Live 4D results hub for all major Malaysian operators.',
        data: {
          kicker: 'RESULTS HUB',
          title: '4D Result Today: Magnum, Toto & Da Ma Cai',
          subtitle: 'Winning numbers published every Wednesday, Saturday and Sunday at 7:00 PM MYT.',
          digits: [4, 8, 2, 6],
        },
      },
      {
        file: '4d-result-today-board-explained',
        type: 'table',
        alt: 'Annotated 4D result board showing 1st, 2nd, 3rd, special and consolation prize sections',
        caption: 'How to read every section of a 4D result board.',
        data: {
          kicker: 'HOW TO READ',
          title: 'Anatomy of a 4D Result Board',
          columns: [
            { label: 'Section', w: 2 },
            { label: 'What it means', w: 4 },
            { label: 'Winning numbers', w: 2.4 },
          ],
          rows: [
            ['1st Prize', 'Top prize. One number, must match all four digits in order.', '4567'],
            ['2nd Prize', 'Runner-up. One number, exact order.', '2210'],
            ['3rd Prize', 'Third place. One number, exact order.', '9081'],
            ['Special (10)', 'Ten numbers. Fixed payout on a Big bet.', '0348 1572 ...'],
            ['Consolation (10)', 'Ten numbers. Fixed payout on a Big bet.', '7712 6049 ...'],
          ],
          note: 'Example digits only. Always match against the live board for your draw date.',
        },
      },
      {
        file: '4d-result-today-3-steps',
        type: 'steps',
        alt: 'Three simple steps to check 4D results today online',
        caption: 'From operator to ticket check in under a minute.',
        data: {
          kicker: 'FAST CHECK',
          title: "Check Today's 4D Result in 3 Steps",
          items: [
            { h: 'Pick your operator', p: 'Choose Magnum 4D, Sports Toto or Da Ma Cai, the three national pools that draw on the same days.' },
            { h: 'Open the board at 7:00 PM MYT', p: 'Results go live right after the draw. Refresh once if the board still shows the previous draw.' },
            { h: 'Match all four digits', p: 'Read them left to right. A permutation bet wins if the digits match in any order.' },
          ],
          note: 'Bookmark this page. It is updated every draw day.',
        },
      },
      {
        file: '4d-result-today-draw-schedule',
        type: 'table',
        alt: '4D draw schedule showing Wednesday, Saturday and Sunday 7pm draws by operator',
        caption: 'When each operator publishes its results.',
        data: {
          kicker: 'SCHEDULE',
          title: 'Draw Days and Result Times',
          columns: [
            { label: 'Operator', w: 2.6 },
            { label: 'Draw days', w: 3 },
            { label: 'Result time', w: 2 },
            { label: 'Region', w: 2.2 },
          ],
          rows: [
            ['Magnum 4D', 'Wednesday, Saturday, Sunday', '7:00 PM MYT', 'Peninsular'],
            ['Sports Toto', 'Wednesday, Saturday, Sunday', '7:00 PM MYT', 'Peninsular'],
            ['Da Ma Cai', 'Wednesday, Saturday, Sunday', '7:00 PM MYT', 'Peninsular'],
            ['Cash Sweep', 'Wednesday, Saturday, Sunday', 'Evening MYT', 'Sarawak'],
            ['Sabah 88 / Sandakan', 'Usually Tue, Thu, Sat, Sun', 'Evening MYT', 'Sabah'],
          ],
          note: 'Special draw days can be added during festive periods. Confirm on the official operator site.',
        },
      },
      {
        file: '4d-result-today-verify-checklist',
        type: 'card',
        alt: 'Checklist to verify 4D results and claim prizes safely',
        caption: 'Five checks before you celebrate.',
        data: {
          kicker: 'BEFORE YOU CLAIM',
          title: 'Verify First, Celebrate Second',
          heading: 'Five checks on every winning ticket',
          bullets: [
            'Confirm the draw date and time on the ticket match the result board.',
            'Match all four digits in exact order (or any order for a permutation bet).',
            'Cross-check the number on the official operator site, not just one source.',
            'Sign the back of the ticket and keep it somewhere safe. It is a bearer document.',
            'Bring IC and the original ticket to claim. Large prizes are paid at operator headquarters.',
          ],
          note: 'Never publish a photo of an unclaimed winning ticket.',
        },
      },
    ],
  },
  {
    folder: '02-4d-results-history',
    slug: '4d-results-history',
    images: [
      {
        file: '4d-results-history-hero',
        type: 'hero',
        alt: '4D results history archive of past Magnum, Sports Toto and Da Ma Cai winning numbers',
        caption: 'Years of past winning numbers in one archive.',
        data: {
          kicker: 'ARCHIVE',
          title: '4D Results History: Past Winning Numbers',
          subtitle: 'Look up any draw by date, operator and prize tier, free and fast.',
          digits: [1, 9, 5, 3],
        },
      },
      {
        file: '4d-results-history-lookup-steps',
        type: 'steps',
        alt: 'Steps to find past 4D results by date in the history archive',
        caption: 'Find any old result in three moves.',
        data: {
          kicker: 'LOOKUP',
          title: 'Find Any Past Result in 3 Moves',
          items: [
            { h: 'Choose operator and game', p: 'Filter by Magnum, Sports Toto or Da Ma Cai first. The same date has three different boards.' },
            { h: 'Jump to the draw date', p: 'Draws fall on Wednesday, Saturday and Sunday, so scroll to the week you need or use the date picker.' },
            { h: 'Read the full 23-number board', p: 'Top three prizes plus 10 special and 10 consolation numbers, all listed for that draw.' },
          ],
          note: 'Use the draw date printed on your ticket, not the date you bought it.',
        },
      },
      {
        file: '4d-results-history-sample',
        type: 'table',
        alt: 'Sample table of historical 4D results with draw date and winning numbers',
        caption: 'What a history row looks like.',
        data: {
          kicker: 'SAMPLE ROWS',
          title: 'History Table Format',
          columns: [
            { label: 'Draw date', w: 2.4 },
            { label: '1st Prize', w: 1.8 },
            { label: '2nd Prize', w: 1.8 },
            { label: '3rd Prize', w: 1.8 },
            { label: 'Operator', w: 2.4 },
          ],
          rows: [
            ['Wed, 30 Sep 2026', '4567', '2210', '9081', 'Magnum 4D'],
            ['Sat, 03 Oct 2026', '3084', '7712', '5590', 'Magnum 4D'],
            ['Sun, 04 Oct 2026', '8125', '4470', '6633', 'Magnum 4D'],
            ['Wed, 30 Sep 2026', '9042', '1188', '7356', 'Sports Toto'],
            ['Sat, 03 Oct 2026', '2761', '5504', '3319', 'Sports Toto'],
          ],
          note: 'Illustrative rows. The live archive holds the real draw data.',
        },
      },
      {
        file: '4d-results-history-draws-per-year',
        type: 'chart',
        alt: 'Chart comparing how many 4D draws take place each year by operator type',
        caption: 'How much history each operator type generates.',
        data: {
          kicker: 'DATA VOLUME',
          title: 'Approximate Draws Available Per Year',
          unitLabel: 'Draws per year (approx.)',
          bars: [
            { label: 'Big 3 pools (3 days/week)', value: 156, display: '156' },
            { label: 'Singapore Pools (3 days/week)', value: 156, display: '156' },
            { label: 'Sabah pools (4 days/week)', value: 208, display: '208' },
            { label: 'Regional daily operators', value: 365, display: '365' },
          ],
          note: 'Special draw days add a handful of extra boards each year.',
        },
      },
      {
        file: '4d-results-history-responsible-use',
        type: 'card',
        alt: 'Guidelines for using historical 4D data responsibly without prediction myths',
        caption: 'What history can and cannot tell you.',
        data: {
          kicker: 'REALITY CHECK',
          title: 'Using History Data Honestly',
          heading: 'Archive data is a record, not a forecast',
          bullets: [
            'Past draws show what happened. They do not change the odds of the next draw.',
            'No number is due or overdue. Every draw is independent.',
            'Use history to verify an old ticket or satisfy curiosity, not to build a system.',
            'Frequency lists describe the past only. The next draw starts from zero.',
            'Track your own spending alongside results if you play regularly.',
          ],
          note: 'Lottery draws are random. Treat the game as entertainment, not income.',
        },
      },
    ],
  },
  {
    folder: '03-4d-prize-structure',
    slug: '4d-prize-structure',
    images: [
      {
        file: '4d-prize-structure-hero',
        type: 'hero',
        alt: '4D prize structure in Malaysia showing Big and Small bet payouts',
        caption: 'Every ringgit figure for Big and Small bets.',
        data: {
          kicker: 'PAYOUTS',
          title: '4D Prize Structure Malaysia Explained',
          subtitle: 'Big vs Small, all five prize tiers, per RM1 staked, with worked examples.',
          digits: [2, 5, 0, 8],
        },
      },
      {
        file: '4d-prize-structure-big-vs-small',
        type: 'table',
        alt: '4D prize structure table listing Big and Small payouts for each prize tier per RM1',
        caption: 'The official payout tiers, side by side.',
        data: {
          kicker: 'PER RM1',
          title: 'Big (Besar) vs Small (Kecil) Payouts',
          columns: [
            { label: 'Prize tier', w: 2.6 },
            { label: 'Big bet', w: 1.7 },
            { label: 'Small bet', w: 1.7 },
            { label: 'Winning numbers', w: 2 },
          ],
          rows: [
            ['1st Prize', 'RM2,500', 'RM3,500', '1'],
            ['2nd Prize', 'RM1,000', 'RM2,000', '1'],
            ['3rd Prize', 'RM500', 'RM1,000', '1'],
            ['Special', 'RM180', 'No payout', '10'],
            ['Consolation', 'RM60', 'No payout', '10'],
          ],
          note: 'Figures are per RM1 stake for Magnum 4D, Sports Toto and Da Ma Cai. Official operator tables govern.',
        },
      },
      {
        file: '4d-prize-structure-rm10-example',
        type: 'table',
        alt: 'Worked example table showing 4D winnings for a RM10 Big or Small bet',
        caption: 'What a RM10 stake actually pays.',
        data: {
          kicker: 'WORKED EXAMPLE',
          title: 'RM10 Stake: What Each Win Pays',
          columns: [
            { label: 'Result', w: 2.6 },
            { label: 'Big pays', w: 2 },
            { label: 'Small pays', w: 2 },
          ],
          rows: [
            ['1st prize', 'RM25,000', 'RM35,000'],
            ['2nd prize', 'RM10,000', 'RM20,000'],
            ['3rd prize', 'RM5,000', 'RM10,000'],
            ['Special number', 'RM1,800', 'RM0'],
            ['Consolation number', 'RM600', 'RM0'],
          ],
          note: 'Payouts scale linearly: stake x the per-RM1 figure. No bonus for larger stakes.',
        },
      },
      {
        file: '4d-prize-structure-calculation-steps',
        type: 'steps',
        alt: 'Step by step guide to calculating 4D prize winnings from stake and bet type',
        caption: 'Calculate your payout in four steps.',
        data: {
          kicker: 'CALCULATE',
          title: 'How Your 4D Payout Is Worked Out',
          items: [
            { h: 'Check your bet type', p: 'Big covers all 23 winning numbers. Small pays more on the top three but nothing on special or consolation.' },
            { h: 'Match the digits in order', p: 'The number must land in the same order you played, unless you bought a permutation or iBet entry.' },
            { h: 'Multiply by your stake', p: 'Per-RM1 payout times your stake. A RM5 Big hit on 1st prize pays 5 x RM2,500 = RM12,500.' },
            { h: 'Claim with the original ticket', p: 'Keep the ticket pristine. Outlet cash limits apply, and big wins are settled at operator headquarters.' },
          ],
          note: 'Check your slip: it prints the bet type, draw date and stake.',
        },
      },
      {
        file: '4d-prize-structure-facts',
        type: 'card',
        alt: 'Key facts about the 4D prize structure and how winnings are paid',
        caption: 'The facts that decide your payout.',
        data: {
          kicker: 'KEY FACTS',
          title: 'Prize Structure Facts to Remember',
          heading: 'Six things that decide what you win',
          bullets: [
            'Every draw publishes 23 winning numbers: 3 top prizes, 10 special, 10 consolation.',
            'A Big bet can win on any of the 23. A Small bet can win only on the top 3.',
            'Small pays 40 percent more on 1st prize. The trade-off is zero coverage below 3rd.',
            'Payouts are linear: RM10 wins ten times the listed figure.',
            'Permutation and iBet entries pay less per combination because the cost is spread.',
            'All three national pools use the same core prize table.',
          ],
          warn: 'Always confirm against the operator published prize table before claiming.',
        },
      },
    ],
  },
  {
    folder: '04-how-to-check-4d-result-online',
    slug: 'how-to-check-4d-result-online',
    images: [
      {
        file: 'how-to-check-4d-result-online-hero',
        type: 'hero',
        alt: 'How to check 4D results online safely on phone and laptop',
        caption: 'Five methods, ranked by reliability.',
        data: {
          kicker: 'TUTORIAL',
          title: 'How to Check 4D Results Online',
          subtitle: 'Five fast methods, and the red flags that tell you a site cannot be trusted.',
          digits: [0, 4, 7, 1],
        },
      },
      {
        file: 'how-to-check-4d-result-online-methods',
        type: 'steps',
        alt: 'Five safe methods to check 4D results online including official sites and apps',
        caption: 'The five methods, most reliable first.',
        data: {
          kicker: 'METHODS',
          title: '5 Ways to Check 4D Results Online',
          items: [
            { h: 'Operator official website', p: 'Magnum, Sports Toto and Da Ma Cai publish the full board on their own sites. This is the source of record.' },
            { h: 'Licensed results aggregators', p: 'Sites such as 4DMalaya collate all operators on one page so you are not tab-hopping between three sites.' },
            { h: 'Official mobile app', p: 'Operator apps give push notifications the moment a board is published. Useful on draw nights.' },
            { h: 'SMS or messaging alerts', p: 'Some outlets and services send results by SMS or chat channel. Confirm the sender is legitimate.' },
            { h: 'Newspaper and outlet boards', p: 'The offline fallback. Next-day papers and printed boards at outlets carry the full result.' },
          ],
          note: 'Whichever method you use, confirm the draw date printed on your ticket.',
        },
      },
      {
        file: 'how-to-check-4d-result-online-official-channels',
        type: 'table',
        alt: 'Table of official websites and apps for checking Magnum, Sports Toto and Da Ma Cai results',
        caption: 'Where the source-of-truth results live.',
        data: {
          kicker: 'OFFICIAL SOURCES',
          title: 'Official Result Channels',
          columns: [
            { label: 'Operator', w: 2.4 },
            { label: 'Website', w: 3.2 },
            { label: 'App', w: 2.6 },
            { label: 'Check first', w: 3 },
          ],
          rows: [
            ['Magnum 4D', 'magnum4d.my', 'Magnum 4D app', 'Draw date + game'],
            ['Sports Toto', 'sportstoto.com.my', 'Sports Toto app', 'Draw date + game'],
            ['Da Ma Cai', 'damacai.com.my', 'Da Ma Cai app', 'Draw date + 4D or 1+3D'],
          ],
          note: 'Confirm the domain yourself before entering any personal information. None is needed to view results.',
        },
      },
      {
        file: 'how-to-check-4d-result-online-red-flags',
        type: 'card',
        alt: 'Red flags of unsafe 4D result websites to avoid',
        caption: 'Walk away when you see these.',
        data: {
          kicker: 'SAFETY',
          title: 'Red Flags on Result Sites',
          heading: 'Six signs a result site is not safe',
          bullets: [
            'No draw date or timestamp on the numbers shown.',
            'It asks you to log in, pay or deposit just to view results.',
            'Popups pushing gambling apps or foreign betting operators.',
            'Links to unlicensed bookies, agents or Telegram betting groups.',
            'Typosquat domains that mimic an operator official spelling.',
            'It requests your IC, bank details or OTP. No result site ever needs these.',
          ],
          warn: 'Viewing results is always free. If a site asks for money or data, close it.',
        },
      },
      {
        file: 'how-to-check-4d-result-online-flow',
        type: 'flow',
        alt: 'Flow diagram from 4D draw time to checking the result on a ticket',
        caption: 'From draw close to verified result.',
        data: {
          kicker: 'TIMELINE',
          title: 'Draw Night Result Flow',
          steps: [
            { h: 'Sales close', p: 'Bet sales stop shortly before the 7pm draw. Check with your outlet.' },
            { h: 'Draw held', p: 'The draw runs at about 7:00 PM MYT on Wed, Sat and Sun.' },
            { h: 'Board published', p: 'Operators post the full 23-number board within minutes.' },
            { h: 'Aggregators update', p: 'Results sites refresh across all operators the same evening.' },
            { h: 'Verify ticket', p: 'Match the draw date and all four digits, then keep the ticket safe.' },
          ],
          note: 'Publication can run a few minutes either side of 7pm. Refresh once before worrying.',
        },
      },
    ],
  },
  {
    folder: '05-4d-draw-schedule',
    slug: '4d-draw-schedule',
    images: [
      {
        file: '4d-draw-schedule-hero',
        type: 'hero',
        alt: '4D draw schedule for Malaysia showing draw days and 7pm result times',
        caption: 'Every draw day, every operator, one page.',
        data: {
          kicker: 'CALENDAR',
          title: '4D Draw Schedule Malaysia',
          subtitle: 'Wednesday, Saturday, Sunday at 7:00 PM MYT, plus special draws and East Malaysian pools.',
          digits: [3, 6, 0, 7],
        },
      },
      {
        file: '4d-draw-schedule-weekly-grid',
        type: 'table',
        alt: 'Weekly grid showing which days each 4D operator holds draws from Monday to Sunday',
        caption: 'Which operator draws on which day.',
        data: {
          kicker: 'WEEK GRID',
          title: 'Draw Days by Operator',
          columns: [
            { label: 'Operator', w: 3 },
            { label: 'Mon', w: 1 },
            { label: 'Tue', w: 1 },
            { label: 'Wed', w: 1 },
            { label: 'Thu', w: 1 },
            { label: 'Fri', w: 1 },
            { label: 'Sat', w: 1 },
            { label: 'Sun', w: 1 },
          ],
          rows: [
            ['Magnum 4D', '-', '-', 'DRAW', '-', '-', 'DRAW', 'DRAW'],
            ['Sports Toto', '-', '-', 'DRAW', '-', '-', 'DRAW', 'DRAW'],
            ['Da Ma Cai', '-', '-', 'DRAW', '-', '-', 'DRAW', 'DRAW'],
            ['Cash Sweep', '-', '-', 'DRAW', '-', '-', 'DRAW', 'DRAW'],
            ['Sabah 88 / Sandakan', '-', 'DRAW', 'DRAW', 'DRAW', '-', 'DRAW', 'DRAW'],
          ],
          note: 'East Malaysian schedules vary. Sabah pools commonly draw Tue, Thu, Sat and Sun. Confirm on the operator site.',
        },
      },
      {
        file: '4d-draw-schedule-draw-evening-timeline',
        type: 'steps',
        alt: 'Timeline of a 4D draw evening from sales close to published results',
        caption: 'What happens on a draw evening.',
        data: {
          kicker: 'DRAW NIGHT',
          title: 'The Draw Evening Timeline',
          items: [
            { h: 'Sales close', p: 'Bets for that draw stop being accepted shortly before the draw. Ask your outlet for its exact cut-off.' },
            { h: 'Draw at 7:00 PM MYT', p: 'The winning 23 numbers are drawn and announced by the operator.' },
            { h: 'Board published', p: 'The official result board goes up within minutes on the operator site and app.' },
            { h: 'Results updated everywhere', p: 'Aggregators refresh all boards the same evening, usually within minutes of the operator.' },
          ],
          note: 'Times are a guide, not a guarantee. Read the timestamp beside the result you are viewing.',
        },
      },
      {
        file: '4d-draw-schedule-draws-per-week',
        type: 'chart',
        alt: 'Bar chart comparing number of 4D draws per week across Malaysian operators',
        caption: 'How many draws each week offers.',
        data: {
          kicker: 'DRAW COUNT',
          title: 'Draws Available Per Week',
          unitLabel: 'Regular draws per week',
          bars: [
            { label: 'Regional daily operators', value: 7, display: '7' },
            { label: 'Sabah 88 / Sandakan (usual)', value: 4, display: '4' },
            { label: 'Magnum / Toto / Da Ma Cai', value: 3, display: '3' },
            { label: 'Cash Sweep', value: 3, display: '3' },
            { label: 'Singapore Pools', value: 3, display: '3' },
          ],
          note: 'Special draws add extra boards on selected dates, especially during festive seasons.',
        },
      },
      {
        file: '4d-draw-schedule-special-draws',
        type: 'card',
        alt: 'Explanation of special 4D draw days added during festive seasons in Malaysia',
        caption: 'Extra draws and how to catch them.',
        data: {
          kicker: 'SPECIAL DRAWS',
          title: 'Special Draw Days Explained',
          heading: 'What to know about non-standard draw dates',
          bullets: [
            'Operators can add extra draw days when the authorities approve them.',
            'They cluster around Chinese New Year, Deepavali, Hari Raya and year-end holidays.',
            'Announcements come from the operators themselves, days or weeks ahead.',
            'The result archive is the fastest proof: if a board exists for that date, it was a real draw.',
            'Your ticket must show the exact draw date. A special draw is a separate draw, not a bonus round.',
          ],
          warn: 'If a site claims a bonus draw that no operator announced, treat it as suspect.',
        },
      },
    ],
  },
];
